
import { BaseAdapter, CollectionDetails } from "./BaseAdapter";
import { GeneratedDocument } from "../types";
import { SchemaField } from "../../types/schemaDesign";

/**
 * An in-memory, ephemeral adapter for stateless generation.
 * This adapter does not persist data to any database.
 * It stores generated documents in memory for the duration of the request.
 */
export class EphemeralAdapter extends BaseAdapter {
	private storage: Map<string, GeneratedDocument[]> = new Map();
	private headers: Map<string, string[]> = new Map();

	constructor() {
		super();
	}

	async connect(): Promise<void> {
		// No-op
	}

	async disconnect(): Promise<void> {
		// Do not clear storage on disconnect for EphemeralAdapter
		// This allows data transfer after generation service finishes
		// this.storage.clear();
		// this.headers.clear();
	}

	async ensureCollection(collectionName: string, schema?: SchemaField[], skipForeignKeys?: boolean): Promise<void> {
		if (!this.storage.has(collectionName)) {
			this.storage.set(collectionName, []);
		}
		if (schema) {
			this.headers.set(collectionName, schema.map(f => f.name));
		}
	}

	async insertDocuments(
		collectionName: string,
		documents: GeneratedDocument[],
		batchSize?: number,
		allowedReferenceFields?: Set<string>,
		schema?: SchemaField[]
	): Promise<(string | number)[]> {
		if (!this.storage.has(collectionName)) {
			this.storage.set(collectionName, []);
		}

		const store = this.storage.get(collectionName)!;
		const ids: (string | number)[] = [];

		for (const doc of documents) {
			store.push(doc);
			ids.push(doc.id);
		}

		return ids;
	}

	async clearCollection(collectionName: string): Promise<void> {
		this.storage.set(collectionName, []);
	}

	async collectionExists(collectionName: string): Promise<boolean> {
		return true; // Always "exists" virtually
	}

	async getCollectionDetails(collectionName: string): Promise<CollectionDetails> {
		return {
			primaryKey: 'id',
			primaryKeyType: 'string'
		};
	}

	async getDocumentCount(collectionName: string): Promise<number> {
		const store = this.storage.get(collectionName);
		return store ? store.length : 0;
	}

	async validateReference(
		collectionName: string,
		fieldName: string,
		value: unknown
	): Promise<boolean> {
		// For ephemeral generation, we assume references generated by the engine are valid
		// We could strictly check this.storage, but dependency order ensures parents exist.
		return true;
	}

	async addForeignKeyConstraints(collectionName: string, schema: SchemaField[]): Promise<void> {
		// No-op
	}

	/**
	 * Retrieve all generated documents for a specific collection.
	 * specific to EphemeralAdapter.
	 */
	public getDocuments(collectionName: string): GeneratedDocument[] {
		return this.storage.get(collectionName) || [];
	}

	/**
	 * Retrieve the entire in-memory database.
	 */
	public getAllData(): Record<string, any[]> {
		const result: Record<string, any[]> = {};
		for (const [name, docs] of this.storage.entries()) {
			result[name] = docs.map(d => d.data);
		}
		return result;
	}
}
