import { SchemaCollection, SchemaRelationship, SchemaField } from "../../types/schemaDesign";
import { GeneratedCode, ORMGenerator, FieldTypeContext } from "./types";

/**
 * Generates Drizzle ORM schema from canvas schema
 */
export class DrizzleGenerator implements ORMGenerator {
	/**
	 * Map Drawline field types to Drizzle column functions
	 */
	private mapFieldType(ctx: FieldTypeContext): string {
		const { fieldType, isPrimaryKey, isSerial } = ctx;

		// Handle serial/auto-increment primary keys
		if (isPrimaryKey && isSerial) {
			return "serial";
		}

		const typeMap: Record<string, string> = {
			string: "text",
			integer: "integer",
			number: "real",
			boolean: "boolean",
			date: "timestamp",
			timestamp: "timestamp",
			timestamptz: "timestamp",
			uuid: "uuid",
			objectid: "text",
			long: "bigint",
			bigint: "bigint",
			decimal: "numeric",
			float: "real",
			json: "json",
			object: "json",
			binary: "text",
			bytes: "text",
		};

		return typeMap[fieldType.toLowerCase()] || "text";
	}

	/**
	 * Generate column modifiers chain
	 */
	private getColumnModifiers(field: SchemaField, ctx: FieldTypeContext): string[] {
		const modifiers: string[] = [];

		if (ctx.isPrimaryKey) {
			modifiers.push("primaryKey()");
		}

		if (!ctx.isNullable && !ctx.isPrimaryKey) {
			modifiers.push("notNull()");
		}

		if (ctx.isUnique && !ctx.isPrimaryKey) {
			modifiers.push("unique()");
		}

		if (ctx.defaultValue !== undefined && ctx.defaultValue !== null && !ctx.isPrimaryKey) {
			const defStr = String(ctx.defaultValue).toLowerCase();
			if (defStr.includes("now()") || defStr.includes("current_timestamp")) {
				modifiers.push("defaultNow()");
			} else if (typeof ctx.defaultValue === "string") {
				modifiers.push(`default("${ctx.defaultValue}")`);
			} else {
				modifiers.push(`default(${ctx.defaultValue})`);
			}
		}

		return modifiers;
	}

	/**
	 * Generate table definition
	 */
	private generateTable(
		collection: SchemaCollection,
		relationships: SchemaRelationship[],
		collectionMap: Map<string, SchemaCollection>
	): string {
		const lines: string[] = [];
		const tableName = collection.name;
		const varName = this.toCamelCase(collection.name);

		lines.push(`export const ${varName} = pgTable("${tableName}", {`);

		// Generate columns
		for (const field of collection.fields) {
			const ctx: FieldTypeContext = {
				fieldType: field.type,
				isPrimaryKey: !!field.isPrimaryKey,
				isForeignKey: !!field.isForeignKey,
				isSerial: !!field.isSerial,
				isNullable: !field.required && !field.isPrimaryKey,
				isUnique: !!field.constraints?.unique,
				defaultValue: field.defaultValue,
				enumValues: field.constraints?.enum,
			};

			const drizzleType = this.mapFieldType(ctx);
			const modifiers = this.getColumnModifiers(field, ctx);

			let columnDef = `  ${field.name}: ${drizzleType}("${field.name}")`;

			// Add modifiers
			for (const mod of modifiers) {
				columnDef += `.${mod}`;
			}

			// Handle foreign key reference
			if (ctx.isForeignKey && field.referencedCollectionId) {
				const targetCollection = collectionMap.get(field.referencedCollectionId);
				if (targetCollection) {
					const targetVarName = this.toCamelCase(targetCollection.name);
					const targetField = field.foreignKeyTarget || "id";
					columnDef += `.references(() => ${targetVarName}.${targetField})`;
				}
			}

			columnDef += ",";
			lines.push(columnDef);
		}

		lines.push("});");
		return lines.join("\n");
	}

	/**
	 * Convert to camelCase
	 */
	private toCamelCase(str: string): string {
		const words = str.split(/[-_]/);
		return words
			.map((word, i) =>
				i === 0
					? word.toLowerCase()
					: word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
			)
			.join("");
	}

	/**
	 * Get all unique Drizzle column type imports needed
	 */
	private getRequiredImports(collections: SchemaCollection[]): string[] {
		const imports = new Set<string>(["pgTable"]);

		for (const collection of collections) {
			for (const field of collection.fields) {
				const ctx: FieldTypeContext = {
					fieldType: field.type,
					isPrimaryKey: !!field.isPrimaryKey,
					isForeignKey: !!field.isForeignKey,
					isSerial: !!field.isSerial,
					isNullable: !field.required,
					isUnique: !!field.constraints?.unique,
				};

				const drizzleType = this.mapFieldType(ctx);
				imports.add(drizzleType);
			}
		}

		return Array.from(imports).sort();
	}

	/**
	 * Generate complete Drizzle schema
	 */
	generate(
		collections: SchemaCollection[],
		relationships: SchemaRelationship[]
	): GeneratedCode {
		const lines: string[] = [];

		// Header
		lines.push("// Generated by Drawline");
		lines.push("// https://drawline.app");
		lines.push("");

		// Imports
		const imports = this.getRequiredImports(collections);
		lines.push(`import { ${imports.join(", ")} } from "drizzle-orm/pg-core";`);
		lines.push("");

		// Create collection map
		const collectionMap = new Map<string, SchemaCollection>();
		for (const col of collections) {
			collectionMap.set(col.id, col);
		}

		// Generate tables
		for (const collection of collections) {
			lines.push(this.generateTable(collection, relationships, collectionMap));
			lines.push("");
		}

		// Generate type exports
		lines.push("// Type exports");
		for (const collection of collections) {
			const varName = this.toCamelCase(collection.name);
			const typeName = this.toPascalCase(collection.name);
			lines.push(`export type ${typeName} = typeof ${varName}.$inferSelect;`);
			lines.push(`export type New${typeName} = typeof ${varName}.$inferInsert;`);
		}

		return {
			filename: "schema.ts",
			content: lines.join("\n"),
			language: "typescript",
		};
	}

	/**
	 * Convert to PascalCase
	 */
	private toPascalCase(str: string): string {
		return str
			.split(/[-_]/)
			.map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
			.join("");
	}
}
